
[build]
  command = "npm run build"
  functions = "netlify/function/"
  publish = "build"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/quezeshow_before"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "https://ay0.site"
  to = "/.netlify/functions/Main2"
  status = 200

[[redirects]]
  from = "/machugi"
  to = "/.netlify/functions/Machugi"
  status = 200

[[redirects]]
  from = "/quezeshow_main"
  to = "/.netlify/functions/Quezeshow_main"
  status = 200

[[redirects]]
  from = "/continue_speaking"
  to = "/.netlify/functions/Continue_speaking"
  status = 200

[[redirects]]
  from = "/new_word_queze"
  to = "/.netlify/functions/New_word_queze"
  status = 200

[[redirects]]
  from = "/community"
  to = "/.netlify/functions/Community"
  status = 200

[[redirects]]
  from = "/guide_main"
  to = "/.netlify/functions/Guide_main"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


