
  [build]
  command = "npm run build"
  functions = "netlify/function/"
  publish = "build"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  from = "/quezeshow_before"
  to = "/.netlify/function/ssr"
  status = 200
  force = true

