
[build]
  command = "npm run build"
  functions = "netlify/function/"
  publish = "build"

[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/quezeshow_before"
  to = "/.netlify/functions/ssr"
  status = 200

[[redirects]]
  from = "/machugi"
  to = "/.netlify/functions/ssrMain"
  status = 200

[[redirects]]
  from = "/quezeshow_before/*"
  to = "/.netlify/functions/ssr/:splat"
  status = 200

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


